var TypeScript1;
!function(TypeScript) {
    var ErrorRecoverySet, AllowedElements, Modifiers, ASTFlags, DeclFlags, ModuleFlags, SymbolFlags, VarFlags, FncFlags, SignatureFlags, TypeFlags, TypeRelationshipFlags, CodeGenTarget, ModuleGenTarget, ErrorRecoverySet1, AllowedElements1, Modifiers1, ASTFlags1, DeclFlags1, ModuleFlags1, SymbolFlags1, VarFlags1, FncFlags1, SignatureFlags1, TypeFlags1, TypeRelationshipFlags1, CodeGenTarget1, ModuleGenTarget1;
    TypeScript.hasFlag = function(val, flag) {
        return (val & flag) != 0;
    }, (ErrorRecoverySet1 = ErrorRecoverySet || (ErrorRecoverySet = {
    }))[ErrorRecoverySet1.None = 0] = "None", ErrorRecoverySet1[ErrorRecoverySet1.Comma = 1] = "Comma", ErrorRecoverySet1[ErrorRecoverySet1.SColon = 2] = "SColon", ErrorRecoverySet1[ErrorRecoverySet1.Asg = 4] = "Asg", ErrorRecoverySet1[ErrorRecoverySet1.BinOp = 8] = "BinOp", ErrorRecoverySet1[ErrorRecoverySet1.RBrack = 16] = "RBrack", ErrorRecoverySet1[ErrorRecoverySet1.RCurly = 32] = "RCurly", ErrorRecoverySet1[ErrorRecoverySet1.RParen = 64] = "RParen", ErrorRecoverySet1[ErrorRecoverySet1.Dot = 128] = "Dot", ErrorRecoverySet1[ErrorRecoverySet1.Colon = 256] = "Colon", ErrorRecoverySet1[ErrorRecoverySet1.PrimType = 512] = "PrimType", ErrorRecoverySet1[ErrorRecoverySet1.AddOp = 1024] = "AddOp", ErrorRecoverySet1[ErrorRecoverySet1.LCurly = 2048] = "LCurly", ErrorRecoverySet1[ErrorRecoverySet1.PreOp = 4096] = "PreOp", ErrorRecoverySet1[ErrorRecoverySet1.RegExp = 8192] = "RegExp", ErrorRecoverySet1[ErrorRecoverySet1.LParen = 16384] = "LParen", ErrorRecoverySet1[ErrorRecoverySet1.LBrack = 32768] = "LBrack", ErrorRecoverySet1[ErrorRecoverySet1.Scope = 65536] = "Scope", ErrorRecoverySet1[ErrorRecoverySet1.In = 131072] = "In", ErrorRecoverySet1[ErrorRecoverySet1.SCase = 262144] = "SCase", ErrorRecoverySet1[ErrorRecoverySet1.Else = 524288] = "Else", ErrorRecoverySet1[ErrorRecoverySet1.Catch = 1048576] = "Catch", ErrorRecoverySet1[ErrorRecoverySet1.Var = 2097152] = "Var", ErrorRecoverySet1[ErrorRecoverySet1.Stmt = 4194304] = "Stmt", ErrorRecoverySet1[ErrorRecoverySet1.While = 8388608] = "While", ErrorRecoverySet1[ErrorRecoverySet1.ID = 16777216] = "ID", ErrorRecoverySet1[ErrorRecoverySet1.Prefix = 33554432] = "Prefix", ErrorRecoverySet1[ErrorRecoverySet1.Literal = 67108864] = "Literal", ErrorRecoverySet1[ErrorRecoverySet1.RLit = 134217728] = "RLit", ErrorRecoverySet1[ErrorRecoverySet1.Func = 268435456] = "Func", ErrorRecoverySet1[ErrorRecoverySet1.EOF = 536870912] = "EOF", ErrorRecoverySet1[ErrorRecoverySet1.TypeScriptS = 1073741824] = "TypeScriptS", ErrorRecoverySet1[ErrorRecoverySet1.ExprStart = 520158210] = "ExprStart", ErrorRecoverySet1[ErrorRecoverySet1.StmtStart = 1608580098] = "StmtStart", ErrorRecoverySet1[ErrorRecoverySet1.Postfix = 49280] = "Postfix", (AllowedElements1 = AllowedElements || (AllowedElements = {
    }))[AllowedElements1.None = 0] = "None", AllowedElements1[AllowedElements1.ModuleDeclarations = 4] = "ModuleDeclarations", AllowedElements1[AllowedElements1.ClassDeclarations = 8] = "ClassDeclarations", AllowedElements1[AllowedElements1.InterfaceDeclarations = 16] = "InterfaceDeclarations", AllowedElements1[AllowedElements1.AmbientDeclarations = 1024] = "AmbientDeclarations", AllowedElements1[AllowedElements1.Properties = 2048] = "Properties", AllowedElements1[AllowedElements1.Global = 1052] = "Global", AllowedElements1[AllowedElements1.QuickParse = 3100] = "QuickParse", (Modifiers1 = Modifiers || (Modifiers = {
    }))[Modifiers1.None = 0] = "None", Modifiers1[Modifiers1.Private = 1] = "Private", Modifiers1[Modifiers1.Public = 2] = "Public", Modifiers1[Modifiers1.Readonly = 4] = "Readonly", Modifiers1[Modifiers1.Ambient = 8] = "Ambient", Modifiers1[Modifiers1.Exported = 16] = "Exported", Modifiers1[Modifiers1.Getter = 32] = "Getter", Modifiers1[Modifiers1.Setter = 64] = "Setter", Modifiers1[Modifiers1.Static = 128] = "Static", (ASTFlags1 = ASTFlags || (ASTFlags = {
    }))[ASTFlags1.None = 0] = "None", ASTFlags1[ASTFlags1.ExplicitSemicolon = 1] = "ExplicitSemicolon", ASTFlags1[ASTFlags1.AutomaticSemicolon = 2] = "AutomaticSemicolon", ASTFlags1[ASTFlags1.Writeable = 4] = "Writeable", ASTFlags1[ASTFlags1.Error = 8] = "Error", ASTFlags1[ASTFlags1.DotLHSPartial = 16] = "DotLHSPartial", ASTFlags1[ASTFlags1.DotLHS = 32] = "DotLHS", ASTFlags1[ASTFlags1.IsStatement = 64] = "IsStatement", ASTFlags1[ASTFlags1.StrictMode = 128] = "StrictMode", ASTFlags1[ASTFlags1.PossibleOptionalParameter = 256] = "PossibleOptionalParameter", ASTFlags1[ASTFlags1.ClassBaseConstructorCall = 512] = "ClassBaseConstructorCall", ASTFlags1[ASTFlags1.OptionalName = 1024] = "OptionalName", ASTFlags1[ASTFlags1.SkipNextRParen = 2048] = "SkipNextRParen", (DeclFlags1 = DeclFlags || (DeclFlags = {
    }))[DeclFlags1.None = 0] = "None", DeclFlags1[DeclFlags1.Exported = 1] = "Exported", DeclFlags1[DeclFlags1.Private = 2] = "Private", DeclFlags1[DeclFlags1.Public = 4] = "Public", DeclFlags1[DeclFlags1.Ambient = 8] = "Ambient", DeclFlags1[DeclFlags1.Static = 16] = "Static", DeclFlags1[DeclFlags1.LocalStatic = 32] = "LocalStatic", DeclFlags1[DeclFlags1.GetAccessor = 64] = "GetAccessor", DeclFlags1[DeclFlags1.SetAccessor = 128] = "SetAccessor", (ModuleFlags1 = ModuleFlags || (ModuleFlags = {
    }))[ModuleFlags1.None = 0] = "None", ModuleFlags1[ModuleFlags1.Exported = 1] = "Exported", ModuleFlags1[ModuleFlags1.Private = 2] = "Private", ModuleFlags1[ModuleFlags1.Public = 4] = "Public", ModuleFlags1[ModuleFlags1.Ambient = 8] = "Ambient", ModuleFlags1[ModuleFlags1.Static = 16] = "Static", ModuleFlags1[ModuleFlags1.LocalStatic = 32] = "LocalStatic", ModuleFlags1[ModuleFlags1.GetAccessor = 64] = "GetAccessor", ModuleFlags1[ModuleFlags1.SetAccessor = 128] = "SetAccessor", ModuleFlags1[ModuleFlags1.IsEnum = 256] = "IsEnum", ModuleFlags1[ModuleFlags1.ShouldEmitModuleDecl = 512] = "ShouldEmitModuleDecl", ModuleFlags1[ModuleFlags1.IsWholeFile = 1024] = "IsWholeFile", ModuleFlags1[ModuleFlags1.IsDynamic = 2048] = "IsDynamic", ModuleFlags1[ModuleFlags1.MustCaptureThis = 4096] = "MustCaptureThis", (SymbolFlags1 = SymbolFlags || (SymbolFlags = {
    }))[SymbolFlags1.None = 0] = "None", SymbolFlags1[SymbolFlags1.Exported = 1] = "Exported", SymbolFlags1[SymbolFlags1.Private = 2] = "Private", SymbolFlags1[SymbolFlags1.Public = 4] = "Public", SymbolFlags1[SymbolFlags1.Ambient = 8] = "Ambient", SymbolFlags1[SymbolFlags1.Static = 16] = "Static", SymbolFlags1[SymbolFlags1.LocalStatic = 32] = "LocalStatic", SymbolFlags1[SymbolFlags1.GetAccessor = 64] = "GetAccessor", SymbolFlags1[SymbolFlags1.SetAccessor = 128] = "SetAccessor", SymbolFlags1[SymbolFlags1.Property = 256] = "Property", SymbolFlags1[SymbolFlags1.Readonly = 512] = "Readonly", SymbolFlags1[SymbolFlags1.ModuleMember = 1024] = "ModuleMember", SymbolFlags1[SymbolFlags1.InterfaceMember = 2048] = "InterfaceMember", SymbolFlags1[SymbolFlags1.ClassMember = 4096] = "ClassMember", SymbolFlags1[SymbolFlags1.BuiltIn = 8192] = "BuiltIn", SymbolFlags1[SymbolFlags1.TypeSetDuringScopeAssignment = 16384] = "TypeSetDuringScopeAssignment", SymbolFlags1[SymbolFlags1.Constant = 32768] = "Constant", SymbolFlags1[SymbolFlags1.Optional = 65536] = "Optional", SymbolFlags1[SymbolFlags1.RecursivelyReferenced = 131072] = "RecursivelyReferenced", SymbolFlags1[SymbolFlags1.Bound = 262144] = "Bound", SymbolFlags1[SymbolFlags1.CompilerGenerated = 524288] = "CompilerGenerated", (VarFlags1 = VarFlags || (VarFlags = {
    }))[VarFlags1.None = 0] = "None", VarFlags1[VarFlags1.Exported = 1] = "Exported", VarFlags1[VarFlags1.Private = 2] = "Private", VarFlags1[VarFlags1.Public = 4] = "Public", VarFlags1[VarFlags1.Ambient = 8] = "Ambient", VarFlags1[VarFlags1.Static = 16] = "Static", VarFlags1[VarFlags1.LocalStatic = 32] = "LocalStatic", VarFlags1[VarFlags1.GetAccessor = 64] = "GetAccessor", VarFlags1[VarFlags1.SetAccessor = 128] = "SetAccessor", VarFlags1[VarFlags1.AutoInit = 256] = "AutoInit", VarFlags1[VarFlags1.Property = 512] = "Property", VarFlags1[VarFlags1.Readonly = 1024] = "Readonly", VarFlags1[VarFlags1.Class = 2048] = "Class", VarFlags1[VarFlags1.ClassProperty = 4096] = "ClassProperty", VarFlags1[VarFlags1.ClassBodyProperty = 8192] = "ClassBodyProperty", VarFlags1[VarFlags1.ClassConstructorProperty = 16384] = "ClassConstructorProperty", VarFlags1[VarFlags1.ClassSuperMustBeFirstCallInConstructor = 32768] = "ClassSuperMustBeFirstCallInConstructor", VarFlags1[VarFlags1.Constant = 65536] = "Constant", VarFlags1[VarFlags1.MustCaptureThis = 131072] = "MustCaptureThis", (FncFlags1 = FncFlags || (FncFlags = {
    }))[FncFlags1.None = 0] = "None", FncFlags1[FncFlags1.Exported = 1] = "Exported", FncFlags1[FncFlags1.Private = 2] = "Private", FncFlags1[FncFlags1.Public = 4] = "Public", FncFlags1[FncFlags1.Ambient = 8] = "Ambient", FncFlags1[FncFlags1.Static = 16] = "Static", FncFlags1[FncFlags1.LocalStatic = 32] = "LocalStatic", FncFlags1[FncFlags1.GetAccessor = 64] = "GetAccessor", FncFlags1[FncFlags1.SetAccessor = 128] = "SetAccessor", FncFlags1[FncFlags1.Definition = 256] = "Definition", FncFlags1[FncFlags1.Signature = 512] = "Signature", FncFlags1[FncFlags1.Method = 1024] = "Method", FncFlags1[FncFlags1.HasReturnExpression = 2048] = "HasReturnExpression", FncFlags1[FncFlags1.CallMember = 4096] = "CallMember", FncFlags1[FncFlags1.ConstructMember = 8192] = "ConstructMember", FncFlags1[FncFlags1.HasSelfReference = 16384] = "HasSelfReference", FncFlags1[FncFlags1.IsFatArrowFunction = 32768] = "IsFatArrowFunction", FncFlags1[FncFlags1.IndexerMember = 65536] = "IndexerMember", FncFlags1[FncFlags1.IsFunctionExpression = 131072] = "IsFunctionExpression", FncFlags1[FncFlags1.ClassMethod = 262144] = "ClassMethod", FncFlags1[FncFlags1.ClassPropertyMethodExported = 524288] = "ClassPropertyMethodExported", (SignatureFlags1 = SignatureFlags || (SignatureFlags = {
    }))[SignatureFlags1.None = 0] = "None", SignatureFlags1[SignatureFlags1.IsIndexer = 1] = "IsIndexer", SignatureFlags1[SignatureFlags1.IsStringIndexer = 2] = "IsStringIndexer", SignatureFlags1[SignatureFlags1.IsNumberIndexer = 4] = "IsNumberIndexer", TypeScript.ToDeclFlags = function(fncOrVarOrSymbolOrModuleFlags) {
        return fncOrVarOrSymbolOrModuleFlags;
    }, (TypeFlags1 = TypeFlags || (TypeFlags = {
    }))[TypeFlags1.None = 0] = "None", TypeFlags1[TypeFlags1.HasImplementation = 1] = "HasImplementation", TypeFlags1[TypeFlags1.HasSelfReference = 2] = "HasSelfReference", TypeFlags1[TypeFlags1.MergeResult = 4] = "MergeResult", TypeFlags1[TypeFlags1.IsEnum = 8] = "IsEnum", TypeFlags1[TypeFlags1.BuildingName = 16] = "BuildingName", TypeFlags1[TypeFlags1.HasBaseType = 32] = "HasBaseType", TypeFlags1[TypeFlags1.HasBaseTypeOfObject = 64] = "HasBaseTypeOfObject", TypeFlags1[TypeFlags1.IsClass = 128] = "IsClass", (TypeRelationshipFlags1 = TypeRelationshipFlags || (TypeRelationshipFlags = {
    }))[TypeRelationshipFlags1.SuccessfulComparison = 0] = "SuccessfulComparison", TypeRelationshipFlags1[TypeRelationshipFlags1.SourceIsNullTargetIsVoidOrUndefined = 1] = "SourceIsNullTargetIsVoidOrUndefined", TypeRelationshipFlags1[TypeRelationshipFlags1.RequiredPropertyIsMissing = 2] = "RequiredPropertyIsMissing", TypeRelationshipFlags1[TypeRelationshipFlags1.IncompatibleSignatures = 4] = "IncompatibleSignatures", TypeRelationshipFlags1[TypeRelationshipFlags1.SourceSignatureHasTooManyParameters = 3] = "SourceSignatureHasTooManyParameters", TypeRelationshipFlags1[TypeRelationshipFlags1.IncompatibleReturnTypes = 16] = "IncompatibleReturnTypes", TypeRelationshipFlags1[TypeRelationshipFlags1.IncompatiblePropertyTypes = 32] = "IncompatiblePropertyTypes", TypeRelationshipFlags1[TypeRelationshipFlags1.IncompatibleParameterTypes = 64] = "IncompatibleParameterTypes", (CodeGenTarget1 = CodeGenTarget || (CodeGenTarget = {
    }))[CodeGenTarget1.ES3 = 0] = "ES3", CodeGenTarget1[CodeGenTarget1.ES5 = 1] = "ES5", (ModuleGenTarget1 = ModuleGenTarget || (ModuleGenTarget = {
    }))[ModuleGenTarget1.Synchronous = 0] = "Synchronous", ModuleGenTarget1[ModuleGenTarget1.Asynchronous = 1] = "Asynchronous", ModuleGenTarget1[ModuleGenTarget1.Local = 2] = "Local", TypeScript.codeGenTarget = CodeGenTarget.ES3, TypeScript.moduleGenTarget = ModuleGenTarget.Synchronous, TypeScript.optimizeModuleCodeGen = !0, TypeScript.flagsToString = function(e, flags) {
        for(var builder = "", i = 1; i < -2147483648; i <<= 1)if ((flags & i) != 0) {
            for(var k in e)if (e[k] == i) {
                builder.length > 0 && (builder += "|"), builder += k;
                break;
            }
        }
        return builder;
    }, TypeScript.ErrorRecoverySet = ErrorRecoverySet, TypeScript.AllowedElements = AllowedElements, TypeScript.Modifiers = Modifiers, TypeScript.ASTFlags = ASTFlags, TypeScript.DeclFlags = DeclFlags, TypeScript.ModuleFlags = ModuleFlags, TypeScript.SymbolFlags = SymbolFlags, TypeScript.VarFlags = VarFlags, TypeScript.FncFlags = FncFlags, TypeScript.SignatureFlags = SignatureFlags, TypeScript.TypeFlags = TypeFlags, TypeScript.TypeRelationshipFlags = TypeRelationshipFlags, TypeScript.CodeGenTarget = CodeGenTarget, TypeScript.ModuleGenTarget = ModuleGenTarget;
}(TypeScript1 || (TypeScript1 = {
}));
