use ast::*;

macro_rules! mk_trait {
    ($($T:ty),*) => {
        /// Crazy trait to make traversal fast again.
        pub trait Pass: $( ::swc_common::Fold<$T> + )* {}
        impl<P> Pass for P
            where P: ?Sized + $( ::swc_common::Fold<$T> +)*{

        }
    };
}

mk_trait!(
    ArrayLit,
    ArrayPat,
    ArrowExpr,
    AssignExpr,
    AssignPat,
    AssignPatProp,
    AssignProp,
    AwaitExpr,
    BinExpr,
    BlockStmt,
    Bool,
    BreakStmt,
    CallExpr,
    CatchClause,
    Class,
    ClassDecl,
    ClassExpr,
    ClassMethod,
    CondExpr,
    ContinueStmt,
    DebuggerStmt,
    DoWhileStmt,
    EmptyStmt,
    ExportAll,
    ExportSpecifier,
    ExprOrSpread,
    FnDecl,
    FnExpr,
    ForInStmt,
    ForOfStmt,
    ForStmt,
    Function,
    GetterProp,
    Ident,
    IfStmt,
    ImportDecl,
    ImportDefault,
    ImportSpecific,
    ImportStarAs,
    KeyValuePatProp,
    KeyValueProp,
    LabeledStmt,
    MemberExpr,
    MetaPropExpr,
    MethodProp,
    Module,
    NamedExport,
    NewExpr,
    Null,
    Number,
    ObjectLit,
    ObjectPat,
    ParenExpr,
    Regex,
    RestPat,
    ReturnStmt,
    SeqExpr,
    SetterProp,
    SpreadElement,
    Str,
    SwitchCase,
    SwitchStmt,
    ThisExpr,
    ThrowStmt,
    TplElement,
    TplLit,
    TryStmt,
    UnaryExpr,
    UpdateExpr,
    VarDecl,
    VarDeclarator,
    WhileStmt,
    WithStmt,
    YieldExpr,
    // enums
    AssignOp,
    BinaryOp,
    BlockStmtOrExpr,
    ClassMethodKind,
    Decl,
    ExportDefaultDecl,
    Expr,
    ExprOrSuper,
    ImportSpecifier,
    Lit,
    ModuleDecl,
    ModuleItem,
    ObjectPatProp,
    Pat,
    PatOrExpr,
    Prop,
    PropName,
    PropOrSpread,
    Stmt,
    UnaryOp,
    UpdateOp,
    VarDeclKind,
    VarDeclOrExpr,
    VarDeclOrPat
);
