var foo = 0,
    async = 1,
    await = 2,
    implements = 3,
    package = 4,
    private = 5,
    protected = 6,
    static = 7,
    yield = 8;
console.log({
    foo,
    0: 0,
    NaN,
    async,
    await,
    false: false,
    implements: implements,
    null: null,
    package: package,
    private: private,
    protected: protected,
    static: static,
    this: this,
    true: true,
    undefined,
    yield,
});
