/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function isReactCompilerRequired(code: Buffer, signal?: AbortSignal | undefined | null): Promise<boolean>

export declare function isReactCompilerRequiredSync(code: Buffer): boolean

export interface TransformOutput {
  code: string
  map?: string
  output?: string
  diagnostics: Array<string>
}

