var ENUM1, ENUM, ENUM11;
(ENUM1 = ENUM11 || (ENUM11 = {
}))[ENUM1.A = 0] = "A", ENUM1[ENUM1.B = 1] = "B", ENUM1[ENUM1[""] = 2] = "", --ENUM, --ENUM11, ENUM--, ENUM11--, --ENUM.A + ENUM.B, ENUM.A + ENUM.B--, --ENUM, --ENUM11, ENUM--, ENUM11--;
