console.log([]);
console.log([]);
console.log([,]);
console.log([, , , , , , , , , , ,]);
console.log([, , , , , , , , , , ,]);
console.log(Array(12));
console.log(Array(12));
console.log(Array(foo));
console.log(Array(foo));
console.log(Array("foo"));
console.log(Array("foo"));
