import _sliced_to_array from "@swc/helpers/src/_sliced_to_array.mjs";
var x;
var y;
var z;
var _x = _sliced_to_array(x, 3), a = _x[0], b = _x[1], c = _x[2];
var _y = _sliced_to_array(y, 3), d = _y[0], e = _y[1], f = _y[2];
var _z = _sliced_to_array(z, 3), g = _z[0], h = _z[1], i = _z[2];
var j1 = x;
var j2 = y;
var j3 = z;
var k1 = x;
var k2 = y;
var k3 = z;
var l1 = x;
var l2 = y;
var l3 = z;
var m1 = x;
var m2 = y;
var m3 = z;
var n1 = x;
var n2 = y;
var n3 = z;
var o1 = x;
var o2 = y;
var o3 = y;
