//// [emitCompoundExponentiationOperator1.ts]
var comp;
comp = Math.pow(comp, 1);
comp = Math.pow(comp, Math.pow(comp, comp));
comp = Math.pow(comp, Math.pow(comp, Math.pow(comp, 2)));
comp = Math.pow(comp, Math.pow(comp, comp) + 2);
comp = Math.pow(comp, Math.pow(comp, comp) - 2);
comp = Math.pow(comp, Math.pow(comp, comp) * 2);
comp = Math.pow(comp, Math.pow(comp, comp) / 2);
comp = Math.pow(comp, Math.pow(comp, comp) % 2);
comp = Math.pow(comp, Math.pow(comp - 2, 5));
comp = Math.pow(comp, Math.pow(comp + 2, 5));
comp = Math.pow(comp, Math.pow(comp * 2, 5));
comp = Math.pow(comp, Math.pow(comp / 2, 5));
comp = Math.pow(comp, Math.pow(comp % 2, 5));
comp = Math.pow(comp, Math.pow(comp, 5 + 2));
comp = Math.pow(comp, Math.pow(comp, 5 - 2));
comp = Math.pow(comp, Math.pow(comp, 5 * 2));
comp = Math.pow(comp, Math.pow(comp, 5 / 2));
comp = Math.pow(comp, Math.pow(comp, 5 % 2));
