import * as swcHelpers from "@swc/helpers";
var o1;
var o1 = swcHelpers.objectSpread({}, undefinedUnion);
var o2;
var o2 = swcHelpers.objectSpread({}, nullUnion);
var o3;
var o3 = swcHelpers.objectSpread({}, undefinedUnion, nullUnion);
var o3 = swcHelpers.objectSpread({}, nullUnion, undefinedUnion);
var o4;
var o4 = swcHelpers.objectSpread({}, undefinedUnion, undefinedUnion);
var o5;
var o5 = swcHelpers.objectSpread({}, nullUnion, nullUnion);
