name: "Git tag release"
description: "Tags a release"
inputs:
  version:
    description: "The version"
    required: true
  ssh-private-key:
    description: "The SSH private key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: "main"

    - uses: ./.github/actions/setup-node
      with:
        cache: "false"

    - name: Install git-cliff
      uses: taiki-e/install-action@4cef1412cce204788f482e778a0b9187f9626a29 # v2.87.21
      with:
        tool: git-cliff@2.8.0

    - name: Install cargo-edit
      uses: taiki-e/install-action@4cef1412cce204788f482e778a0b9187f9626a29 # v2.87.21
      with:
        tool: cargo-edit@0.12.2

    - name: "Setup jq"
      uses: dcarbone/install-jq-action@8867ddb4788346d7c22b72ea2e2ffe4d514c7bcb # v2.1.0
      with:
        version: "1.7"
        force: true

    - uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Create git tag commit
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.version }}
      run: |
        ./scripts/publish.sh "$RELEASE_VERSION"
