name: "Git tag release"
description: "Tags a release"
inputs:
  version:
    description: "The version"
    required: true
  ssh-private-key:
    description: "The SSH private key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: "main"

    - uses: ./.github/actions/setup-node
      with:
        cache: "false"

    - name: Install git-cliff
      uses: taiki-e/install-action@3235f8901fd37ffed0052b276cec25a362fb82e9 # v2
      with:
        tool: git-cliff@2.8.0

    - name: Install cargo-edit
      uses: taiki-e/install-action@3235f8901fd37ffed0052b276cec25a362fb82e9 # v2
      with:
        tool: cargo-edit@0.12.2

    - name: "Setup jq"
      uses: dcarbone/install-jq-action@8867ddb4788346d7c22b72ea2e2ffe4d514c7bcb # v2
      with:
        version: "1.7"
        force: true

    - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Create git tag commit
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.version }}
      run: |
        ./scripts/publish.sh "$RELEASE_VERSION"
