// @target: es5
var temp1;
Math.pow(temp, 3);
Math.pow(--temp, 3);
Math.pow(++temp, 3);
Math.pow(temp--, 3);
Math.pow(temp++, 3);
Math.pow(1, Math.pow(--temp, 3));
Math.pow(1, Math.pow(++temp, 3));
Math.pow(1, Math.pow(temp--, 3));
Math.pow(1, Math.pow(temp++, 3));
Math.pow(void --temp1, 3);
Math.pow(void temp1--, 3);
Math.pow(void 3, 4);
Math.pow(void temp1++, 4);
Math.pow(void temp1--, 4);
Math.pow(1, Math.pow(void --temp1, 3));
Math.pow(1, Math.pow(void temp1--, 3));
Math.pow(1, Math.pow(void 3, 4));
Math.pow(1, Math.pow(void temp1++, 4));
Math.pow(1, Math.pow(void temp1--, 4));
Math.pow(~--temp1, 3);
Math.pow(~temp1--, 3);
Math.pow(~3, 4);
Math.pow(~temp1++, 4);
Math.pow(~temp1--, 4);
Math.pow(1, Math.pow(~--temp1, 3));
Math.pow(1, Math.pow(~temp1--, 3));
Math.pow(1, Math.pow(~3, 4));
Math.pow(1, Math.pow(~temp1++, 4));
Math.pow(1, Math.pow(~temp1--, 4));
