console.log(10);
console.log(20);
console.log(void 0);
console.log(10);
console.log(20);
console.log(void 0);
console.log(10);
console.log(20);
console.log(void 0);
console.log(10);
console.log(20);
console.log(void 0);
