// Loaded from https://deno.land/x/graphql_deno@v15.0.0/lib/version.js


/**
 * Note: This file is autogenerated using "resources/gen-version.js" script and
 * automatically updated by "yarn version" command.
 */

/**
 * A string containing the version of the GraphQL.js library
 */
export const version = '15.0.0';
/**
 * An object containing the components of the GraphQL.js version string
 */

export const versionInfo = Object.freeze({
  major: 15,
  minor: 0,
  patch: 0,
  preReleaseTag: null
});