var _foo, _a_b_c_d, _a_b, _a_b_c_d1, _a_b_c, _a_b_c_d2, _a_b_c1, _orders_, _orders_1, _orders, _client, _orders_client_key, _a, _c, _a1;
(_foo = foo) === null || _foo === void 0 ? void 0 : _foo.bar;
(_a_b_c_d = (_a_b = a) === null || _a_b === void 0 ? void 0 : _a_b.b.c) === null || _a_b_c_d === void 0 ? void 0 : _a_b_c_d.d.e;
(_a_b_c_d1 = (_a_b_c = a.b) === null || _a_b_c === void 0 ? void 0 : _a_b_c.c.d) === null || _a_b_c_d1 === void 0 ? void 0 : _a_b_c_d1.e;
(_a_b_c_d2 = (_a_b_c1 = a.b.c) === null || _a_b_c1 === void 0 ? void 0 : _a_b_c1.d) === null || _a_b_c_d2 === void 0 ? void 0 : _a_b_c_d2.e;
(_orders_ = orders) === null || _orders_ === void 0 ? void 0 : _orders_[0].price;
(_orders_1 = (_orders = orders) === null || _orders === void 0 ? void 0 : _orders[0]) === null || _orders_1 === void 0 ? void 0 : _orders_1.price;
orders[(_client = client) === null || _client === void 0 ? void 0 : _client.key].price;
(_orders_client_key = orders[client.key]) === null || _orders_client_key === void 0 ? void 0 : _orders_client_key.price;
(0, (_a = a) === null || _a === void 0 ? void 0 : _a.b).c;
(0, (_c = (0, (_a1 = a) === null || _a1 === void 0 ? void 0 : _a1.b).c) === null || _c === void 0 ? void 0 : _c.d).e;
