(function (a) {});
(function ([a]) {});
(function ([a, b]) {});
(function ([[a]]) {});
(function ([[a, b]]) {});
(function ([a, [b]]) {});
(function ([[b], a]) {});
(function ({ a: a }) {});
(function ({ a: a, b: b }) {});
(function ([{ a: a }]) {});
(function ([{ a: a, b: b }]) {});
(function ([a, { b: b }]) {});
(function ([{ b: b }, a]) {});
([a]) => {};
([a, b]) => {};
({ a: a }) => {};
({ a: a, b: b, c: c, d: d, e: e }) => {};
([a]) => b;
([a, b]) => c;
({ a: a }) => b;
({ a: a, b: b }) => c;
