(function(a) {});
(function([a]) {});
(function([a, b1]) {});
(function([[a]]) {});
(function([[a, b1]]) {});
(function([a, [b1]]) {});
(function([[b1], a]) {});
(function({ a: a  }) {});
(function({ a: a , b: b1  }) {});
(function([{ a: a  }]) {});
(function([{ a: a , b: b1  }]) {});
(function([a, { b: b1  }]) {});
(function([{ b: b1  }, a]) {});
([a])=>{};
([a, b1])=>{};
({ a: a  })=>{};
({ a: a , b: b1 , c: c1 , d: d , e: e  })=>{};
([a])=>b;
([a, b1])=>c;
({ a: a  })=>b;
({ a: a , b: b1  })=>c;
