const foo = id("something");
console.log("negative cases");
null === foo || null === foo ? bar : foo;
void 0 === foo || void 0 === foo ? bar : foo;
null === foo || void 0 === foo ? foo : bar;
null === some_global || void 0 === some_global ? bar : some_global;
console.log("positive cases");
foo ?? bar;
foo ?? bar;
foo ?? bar;
