var _foo_bar, _foo_bar1, _foo_bar_baz, _foo_bar2, _foo_bar_baz1, _foo_bar3, _foo_bar_baz2, _foo_bar4;
foo == null ? void 0 : foo(foo);
foo == null ? void 0 : foo.bar();
foo.bar == null ? void 0 : foo.bar.call(foo, foo.bar, false);
foo == null ? void 0 : (_foo_bar = foo.bar) == null ? void 0 : _foo_bar.call(foo, foo.bar, true);
foo.bar.baz == null ? void 0 : foo.bar.baz.call(foo.bar);
(_foo_bar1 = foo.bar) == null ? void 0 : _foo_bar1.baz();
(_foo_bar2 = foo.bar) == null ? void 0 : (_foo_bar_baz = _foo_bar2.baz) == null ? void 0 : _foo_bar_baz.call(_foo_bar2);
foo == null ? void 0 : foo.bar.baz();
foo == null ? void 0 : (_foo_bar_baz1 = foo.bar.baz) == null ? void 0 : _foo_bar_baz1.call(foo.bar);
foo == null ? void 0 : (_foo_bar3 = foo.bar) == null ? void 0 : _foo_bar3.baz();
foo == null ? void 0 : (_foo_bar4 = foo.bar) == null ? void 0 : (_foo_bar_baz2 = _foo_bar4.baz) == null ? void 0 : _foo_bar_baz2.call(_foo_bar4);
