import { type } from 'mod'
import type { type } from 'mod'
import { type foo } from 'mod'
import { type as } from 'mod'
import { type foo as bar } from 'mod'
import { type foo as as } from 'mod'
import { type as as } from 'mod'
import { type as foo } from 'mod'
import { type as type } from 'mod'
import { type as as foo } from 'mod'
import { type as as as } from 'mod'
import { type type as as } from 'mod'
