use swc_ecma_ast::*;

fail_todo!(TsInterfaceDecl);
fail_todo!(TsTypeAliasDecl);
fail_todo!(TsEnumDecl);
fail_todo!(TsModuleDecl);
fail_todo!(TsImportEqualsDecl);
fail_todo!(TsExportAssignment);
fail_todo!(TsNamespaceExportDecl);
fail_todo!(TsTypeAssertion);
fail_todo!(TsConstAssertion);
fail_todo!(TsNonNullExpr);
fail_todo!(TsAsExpr);
fail_todo!(TsInstantiation);
fail_todo!(TsType);
fail_todo!(TsTypeAnn);
fail_todo!(TsTypeParamInstantiation);
fail_todo!(TsTypeParamDecl);
fail_todo!(TsExprWithTypeArgs);
fail_todo!(TsIndexSignature);
fail_todo!(TsParamProp);
fail_todo!(TsSatisfiesExpr);
