/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getTargetTriple(): string

export declare function initCustomTraceSubscriber(traceOutFilePath?: string | undefined | null): void

export declare function minify(code: Buffer, opts: Buffer, extras: NapiMinifyExtra, signal?: AbortSignal | undefined | null): Promise<TransformOutput>

export declare function minifySync(code: Buffer, opts: Buffer, extras: NapiMinifyExtra): TransformOutput

export interface NapiMinifyExtra {
  mangleNameCache?: object
}

export declare function newMangleNameCache(): object

export interface TransformOutput {
  code: string
  map?: string
  output?: string
  diagnostics: Array<string>
}

/** Hack for `Type Generation` */
export interface TransformOutput {
  code: string
  map?: string
}

