var _foo_bar, _foo_bar1, _foo_bar_baz, _foo_bar2, _foo_bar_baz1, _foo_bar3, _foo_bar_baz2, _foo_bar4, _foo_bar_baz3, _foo_bar5;
foo == null ? void 0 : foo[foo];
foo == null ? void 0 : foo.bar[0];
(_foo_bar = foo.bar) == null ? void 0 : _foo_bar[foo == null ? void 0 : foo.bar];
foo == null ? void 0 : (_foo_bar1 = foo.bar) == null ? void 0 : _foo_bar1[foo == null ? void 0 : foo.bar];
(_foo_bar_baz = foo.bar.baz) == null ? void 0 : _foo_bar_baz.d;
(_foo_bar2 = foo.bar) == null ? void 0 : _foo_bar2.baz.d;
(_foo_bar3 = foo.bar) == null ? void 0 : (_foo_bar_baz1 = _foo_bar3.baz) == null ? void 0 : _foo_bar_baz1.d;
foo == null ? void 0 : foo.bar.baz.d;
foo == null ? void 0 : (_foo_bar_baz2 = foo.bar.baz) == null ? void 0 : _foo_bar_baz2.d;
foo == null ? void 0 : (_foo_bar4 = foo.bar) == null ? void 0 : _foo_bar4.baz.d;
foo == null ? void 0 : (_foo_bar5 = foo.bar) == null ? void 0 : (_foo_bar_baz3 = _foo_bar5.baz) == null ? void 0 : _foo_bar_baz3.d;
