console.log(Math.pow(NaN, NaN));
console.log(Math.pow(NaN, Infinity));
console.log(Math.pow(NaN, 2));
console.log(Math.pow(NaN, 1));
console.log(Math.pow(NaN, 0));
console.log(Math.pow(NaN, 0.5));
console.log(Math.pow(NaN, -Infinity));
console.log(Math.pow(NaN, -1));
console.log(Math.pow(NaN, -0));
console.log(Math.pow(Infinity, NaN));
console.log(Math.pow(Infinity, Infinity));
console.log(Math.pow(Infinity, 2));
console.log(Math.pow(Infinity, 1));
console.log(Math.pow(Infinity, 0));
console.log(Math.pow(Infinity, 0.5));
console.log(Math.pow(Infinity, -Infinity));
console.log(Math.pow(Infinity, -1));
console.log(Math.pow(Infinity, -0));
console.log(Math.pow(2, NaN));
console.log(Math.pow(2, Infinity));
console.log(Math.pow(2, 2));
console.log(Math.pow(2, 1));
console.log(Math.pow(2, 0));
console.log(Math.pow(2, 0.5));
console.log(Math.pow(2, -Infinity));
console.log(Math.pow(2, -1));
console.log(Math.pow(2, -0));
console.log(Math.pow(1, NaN));
console.log(Math.pow(1, Infinity));
console.log(Math.pow(1, 2));
console.log(Math.pow(1, 1));
console.log(Math.pow(1, 0));
console.log(Math.pow(1, 0.5));
console.log(Math.pow(1, -Infinity));
console.log(Math.pow(1, -1));
console.log(Math.pow(1, -0));
console.log(Math.pow(0.5, NaN));
console.log(Math.pow(0.5, Infinity));
console.log(Math.pow(0.5, 2));
console.log(Math.pow(0.5, 1));
console.log(Math.pow(0.5, 0));
console.log(Math.pow(0.5, 0.5));
console.log(Math.pow(0.5, -Infinity));
console.log(Math.pow(0.5, -1));
console.log(Math.pow(0.5, -0));
console.log(Math.pow(0, NaN));
console.log(Math.pow(0, Infinity));
console.log(Math.pow(0, 2));
console.log(Math.pow(0, 1));
console.log(Math.pow(0, 0));
console.log(Math.pow(0, 0.5));
console.log(Math.pow(0, -Infinity));
console.log(Math.pow(0, -1));
console.log(Math.pow(0, -0));
console.log(Math.pow(-Infinity, NaN));
console.log(Math.pow(-Infinity, Infinity));
console.log(Math.pow(-Infinity, 2));
console.log(Math.pow(-Infinity, 1));
console.log(Math.pow(-Infinity, 0));
console.log(Math.pow(-Infinity, 0.5));
console.log(Math.pow(-Infinity, -Infinity));
console.log(Math.pow(-Infinity, -1));
console.log(Math.pow(-Infinity, -0));
console.log(Math.pow(-1, NaN));
console.log(Math.pow(-1, Infinity));
console.log(Math.pow(-1, 2));
console.log(Math.pow(-1, 1));
console.log(Math.pow(-1, 0));
console.log(Math.pow(-1, 0.5));
console.log(Math.pow(-1, -Infinity));
console.log(Math.pow(-1, -1));
console.log(Math.pow(-1, -0));
console.log(Math.pow(-0, NaN));
console.log(Math.pow(-0, Infinity));
console.log(Math.pow(-0, 2));
console.log(Math.pow(-0, 1));
console.log(Math.pow(-0, 0));
console.log(Math.pow(-0, 0.5));
console.log(Math.pow(-0, -Infinity));
console.log(Math.pow(-0, -1));
console.log(Math.pow(-0, -0));

console.log("----");

console.log(NaN ** NaN);
console.log(NaN ** Infinity);
console.log(NaN ** 2);
console.log(NaN ** 1);
console.log(NaN ** 0);
console.log(NaN ** 0.5);
console.log(NaN ** -Infinity);
console.log(NaN ** -1);
console.log(NaN ** -0);
console.log(Infinity ** NaN);
console.log(Infinity ** Infinity);
console.log(Infinity ** 2);
console.log(Infinity ** 1);
console.log(Infinity ** 0);
console.log(Infinity ** 0.5);
console.log(Infinity ** -Infinity);
console.log(Infinity ** -1);
console.log(Infinity ** -0);
console.log(2 ** NaN);
console.log(2 ** Infinity);
console.log(2 ** 2);
console.log(2 ** 1);
console.log(2 ** 0);
console.log(2 ** 0.5);
console.log(2 ** -Infinity);
console.log(2 ** -1);
console.log(2 ** -0);
console.log(1 ** NaN);
console.log(1 ** Infinity);
console.log(1 ** 2);
console.log(1 ** 1);
console.log(1 ** 0);
console.log(1 ** 0.5);
console.log(1 ** -Infinity);
console.log(1 ** -1);
console.log(1 ** -0);
console.log(0.5 ** NaN);
console.log(0.5 ** Infinity);
console.log(0.5 ** 2);
console.log(0.5 ** 1);
console.log(0.5 ** 0);
console.log(0.5 ** 0.5);
console.log(0.5 ** -Infinity);
console.log(0.5 ** -1);
console.log(0.5 ** -0);
console.log(0 ** NaN);
console.log(0 ** Infinity);
console.log(0 ** 2);
console.log(0 ** 1);
console.log(0 ** 0);
console.log(0 ** 0.5);
console.log(0 ** -Infinity);
console.log(0 ** -1);
console.log(0 ** -0);
console.log((-Infinity) ** NaN);
console.log((-Infinity) ** Infinity);
console.log((-Infinity) ** 2);
console.log((-Infinity) ** 1);
console.log((-Infinity) ** 0);
console.log((-Infinity) ** 0.5);
console.log((-Infinity) ** -Infinity);
console.log((-Infinity) ** -1);
console.log((-Infinity) ** -0);
console.log((-1) ** NaN);
console.log((-1) ** Infinity);
console.log((-1) ** 2);
console.log((-1) ** 1);
console.log((-1) ** 0);
console.log((-1) ** 0.5);
console.log((-1) ** -Infinity);
console.log((-1) ** -1);
console.log((-1) ** -0);
console.log((-0) ** NaN);
console.log((-0) ** Infinity);
console.log((-0) ** 2);
console.log((-0) ** 1);
console.log((-0) ** 0);
console.log((-0) ** 0.5);
console.log((-0) ** -Infinity);
console.log((-0) ** -1);
console.log((-0) ** -0);
