console.log(NaN);
console.log(Math.pow(NaN, 1 / 0));
console.log(NaN);
console.log(NaN);
console.log(1);
console.log(NaN);
console.log(Math.pow(NaN, -1 / 0));
console.log(NaN);
console.log(1);
console.log(Math.pow(1 / 0, NaN));
console.log(Math.pow(1 / 0, 1 / 0));
console.log(Math.pow(1 / 0, 2));
console.log(Math.pow(1 / 0, 1));
console.log(Math.pow(1 / 0, 0));
console.log(Math.pow(1 / 0, 0.5));
console.log(Math.pow(1 / 0, -1 / 0));
console.log(Math.pow(1 / 0, -1));
console.log(Math.pow(1 / 0, -0));
console.log(NaN);
console.log(Math.pow(2, 1 / 0));
console.log(4);
console.log(2);
console.log(1);
console.log(1.4142135623730951);
console.log(Math.pow(2, -1 / 0));
console.log(0.5);
console.log(1);
console.log(NaN);
console.log(Math.pow(1, 1 / 0));
console.log(1);
console.log(1);
console.log(1);
console.log(1);
console.log(Math.pow(1, -1 / 0));
console.log(1);
console.log(1);
console.log(NaN);
console.log(Math.pow(0.5, 1 / 0));
console.log(0.25);
console.log(0.5);
console.log(1);
console.log(0.7071067811865476);
console.log(Math.pow(0.5, -1 / 0));
console.log(2);
console.log(1);
console.log(NaN);
console.log(Math.pow(0, 1 / 0));
console.log(0);
console.log(0);
console.log(1);
console.log(0);
console.log(Math.pow(0, -1 / 0));
console.log(Infinity);
console.log(1);
console.log(Math.pow(-1 / 0, NaN));
console.log(Math.pow(-1 / 0, 1 / 0));
console.log(Math.pow(-1 / 0, 2));
console.log(Math.pow(-1 / 0, 1));
console.log(Math.pow(-1 / 0, 0));
console.log(Math.pow(-1 / 0, 0.5));
console.log(Math.pow(-1 / 0, -1 / 0));
console.log(Math.pow(-1 / 0, -1));
console.log(Math.pow(-1 / 0, -0));
console.log(NaN);
console.log(Math.pow(-1, 1 / 0));
console.log(1);
console.log(-1);
console.log(1);
console.log(NaN);
console.log(Math.pow(-1, -1 / 0));
console.log(-1);
console.log(1);
console.log(NaN);
console.log(Math.pow(-0, 1 / 0));
console.log(0);
console.log(-0);
console.log(1);
console.log(0);
console.log(Math.pow(-0, -1 / 0));
console.log(-Infinity);
console.log(1);
console.log("----");
console.log(NaN);
console.log(NaN);
console.log(NaN);
console.log(NaN);
console.log(1);
console.log(NaN);
console.log(NaN);
console.log(NaN);
console.log(1);
console.log(NaN);
console.log(Infinity);
console.log(Infinity);
console.log(Infinity);
console.log(1);
console.log(Infinity);
console.log(0);
console.log(0);
console.log(1);
console.log(NaN);
console.log(Infinity);
console.log(4);
console.log(2);
console.log(1);
console.log(1.4142135623730951);
console.log(0);
console.log(0.5);
console.log(1);
console.log(NaN);
console.log(NaN);
console.log(1);
console.log(1);
console.log(1);
console.log(1);
console.log(NaN);
console.log(1);
console.log(1);
console.log(NaN);
console.log(0);
console.log(0.25);
console.log(0.5);
console.log(1);
console.log(0.7071067811865476);
console.log(Infinity);
console.log(2);
console.log(1);
console.log(NaN);
console.log(0);
console.log(0);
console.log(0);
console.log(1);
console.log(0);
console.log(Infinity);
console.log(Infinity);
console.log(1);
console.log(NaN);
console.log(Infinity);
console.log(Infinity);
console.log(-Infinity);
console.log(1);
console.log(Infinity);
console.log(0);
console.log(-0);
console.log(1);
console.log(NaN);
console.log(NaN);
console.log(1);
console.log(-1);
console.log(1);
console.log(NaN);
console.log(NaN);
console.log(-1);
console.log(1);
console.log(NaN);
console.log(0);
console.log(0);
console.log(-0);
console.log(1);
console.log(0);
console.log(Infinity);
console.log(-Infinity);
console.log(1);
