#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

# Remove empty directories
if command -v find &> /dev/null
then
    find . -name '.DS_Store' -type f -delete
    find . -type d -empty -delete
fi
