use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use anyhow::{bail, Context, Result};

const GENERATED_HEADER: &str =
    "// This file is generated by `cargo codegen helpers`. DO NOT MODIFY.\n";
const HELPER_BITMAP_BITS: usize = 128;

#[derive(Debug)]
pub struct Config {
    pub input_dir: PathBuf,
    pub output_dir: PathBuf,
}

#[derive(Debug)]
struct Helper {
    module_name: String,
    ident: String,
    source: String,
    deps: Vec<String>,
}

pub fn generate(config: Config) -> Result<Vec<PathBuf>> {
    let input_dir = config
        .input_dir
        .canonicalize()
        .context("failed to canonicalize helper input directory")?;

    let ordered_modules = read_index_order(&input_dir)?;
    let available_modules = read_available_modules(&input_dir)?;

    let ordered_set = ordered_modules.iter().collect::<BTreeSet<_>>();
    for module_name in &available_modules {
        if !ordered_set.contains(module_name) {
            bail!(
                "helper `{module_name}` exists in packages/helpers/esm but is missing from \
                 index.js"
            );
        }
    }

    let mut helpers = Vec::with_capacity(ordered_modules.len());
    for module_name in &ordered_modules {
        if !available_modules.contains(module_name) {
            bail!("helper `{module_name}` is exported from index.js but the file is missing");
        }

        let path = input_dir.join(format!("{module_name}.js"));
        helpers.push(parse_helper(module_name, &path)?);
    }

    validate_deps(&helpers)?;
    let inline_deps = compute_inline_deps(&helpers)?;

    fs::create_dir_all(&config.output_dir)
        .with_context(|| format!("failed to create output directory: {:?}", config.output_dir))?;

    let expected_files = helpers
        .iter()
        .map(|helper| format!("{}.rs", helper.module_name))
        .chain(std::iter::once("mod.rs".into()))
        .collect::<BTreeSet<_>>();

    for entry in fs::read_dir(&config.output_dir)
        .with_context(|| format!("failed to read output directory: {:?}", config.output_dir))?
    {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
            continue;
        }

        let file_name = path
            .file_name()
            .and_then(|file_name| file_name.to_str())
            .context("generated helper path is not utf-8")?;

        if !expected_files.contains(file_name) {
            fs::remove_file(&path)
                .with_context(|| format!("failed to remove stale generated helper: {path:?}"))?;
        }
    }

    let mut written = Vec::with_capacity(helpers.len() + 1);
    let mod_rs = config.output_dir.join("mod.rs");
    fs::write(&mod_rs, generate_mod_rs(&helpers))
        .with_context(|| format!("failed to write generated helper module: {mod_rs:?}"))?;
    written.push(mod_rs);

    for (helper, inline_deps) in helpers.iter().zip(inline_deps) {
        let output = config.output_dir.join(format!("{}.rs", helper.module_name));
        fs::write(&output, generate_helper_rs(helper, inline_deps))
            .with_context(|| format!("failed to write generated helper file: {output:?}"))?;
        written.push(output);
    }

    Ok(written)
}

fn read_index_order(input_dir: &Path) -> Result<Vec<String>> {
    let index_path = input_dir.join("index.js");
    let index = fs::read_to_string(&index_path)
        .with_context(|| format!("failed to read helper index: {index_path:?}"))?;
    let mut modules = Vec::new();

    for line in index.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("export { _ as ") else {
            continue;
        };

        let Some((exported, rest)) = rest.split_once(" } from \"./") else {
            bail!("unsupported helper index export line: `{line}`");
        };
        let Some(source) = rest.strip_suffix(".js\";") else {
            bail!("unsupported helper index export source: `{line}`");
        };

        if exported != source {
            bail!("helper index exports `{exported}` from `{source}`, but they must match");
        }

        modules.push(exported.to_string());
    }

    if modules.is_empty() {
        bail!("helper index did not contain any helper exports");
    }

    Ok(modules)
}

fn read_available_modules(input_dir: &Path) -> Result<BTreeSet<String>> {
    let mut modules = BTreeSet::new();

    for entry in fs::read_dir(input_dir)
        .with_context(|| format!("failed to read helper input directory: {input_dir:?}"))?
    {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("js") {
            continue;
        }

        let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
            bail!("helper path is not utf-8: {path:?}");
        };

        if stem == "index" {
            continue;
        }

        if !stem.starts_with('_') {
            bail!("helper file name must start with `_`: {path:?}");
        }

        modules.insert(stem.to_string());
    }

    Ok(modules)
}

fn parse_helper(module_name: &str, path: &Path) -> Result<Helper> {
    let code = fs::read_to_string(path)
        .with_context(|| format!("failed to read helper source: {path:?}"))?;

    let mut deps = Vec::new();
    let mut stripped = Vec::new();
    let mut export_count = 0usize;

    for line in code.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("import ") {
            deps.push(parse_import(module_name, trimmed)?);
            continue;
        }

        if trimmed.starts_with("export ") {
            let expected = format!("export {{ {module_name} as _ }};");
            if trimmed != expected {
                bail!("helper `{module_name}` must export exactly `{expected}`, found `{trimmed}`");
            }

            export_count += 1;
            continue;
        }

        stripped.push(line);
    }

    if export_count != 1 {
        bail!("helper `{module_name}` must have exactly one export, found {export_count}");
    }

    let mut source = stripped.join("\n");
    source = source.trim_matches('\n').to_string();
    source.push('\n');

    let function_head = format!("function {module_name}(");
    if !source.contains(&function_head) {
        bail!("helper `{module_name}` must define `{function_head}`");
    }

    if source.lines().any(|line| {
        line.trim_start().starts_with("import ") || line.trim_start().starts_with("export ")
    }) {
        bail!("helper `{module_name}` still contains module syntax after stripping");
    }

    let first_function = source
        .find("function ")
        .context("helper source must contain a function declaration")?;
    let prelude = &source[..first_function];
    for dep in &deps {
        if prelude.contains(dep) {
            bail!(
                "helper `{module_name}` references dependency `{dep}` before the first function \
                 declaration; helper order would become significant"
            );
        }
    }

    let ident = module_name
        .strip_prefix('_')
        .context("helper module name must start with `_`")?
        .to_string();
    if !is_valid_helper_ident(&ident) {
        bail!("invalid helper module name: {module_name}");
    }

    Ok(Helper {
        module_name: module_name.to_string(),
        ident,
        source,
        deps,
    })
}

fn is_valid_helper_ident(ident: &str) -> bool {
    if ident.is_empty() || ident.split('_').any(|part| part.is_empty()) || is_rust_keyword(ident) {
        return false;
    }

    ident
        .bytes()
        .all(|byte| byte == b'_' || byte.is_ascii_lowercase() || byte.is_ascii_digit())
}

fn is_rust_keyword(ident: &str) -> bool {
    matches!(
        ident,
        "Self"
            | "abstract"
            | "as"
            | "async"
            | "await"
            | "become"
            | "box"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "do"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "final"
            | "fn"
            | "for"
            | "gen"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "macro"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "override"
            | "priv"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "typeof"
            | "unsafe"
            | "unsized"
            | "use"
            | "virtual"
            | "where"
            | "while"
            | "yield"
    )
}

fn parse_import(module_name: &str, line: &str) -> Result<String> {
    let Some(rest) = line.strip_prefix("import { _ as ") else {
        bail!("unsupported import in helper `{module_name}`: `{line}`");
    };

    let Some((binding, rest)) = rest.split_once(" } from \"./") else {
        bail!("unsupported import in helper `{module_name}`: `{line}`");
    };

    let Some(source) = rest.strip_suffix(".js\";") else {
        bail!("unsupported import source in helper `{module_name}`: `{line}`");
    };

    if binding != source {
        bail!(
            "helper `{module_name}` imports `{binding}` from `{source}`, but the binding must \
             match the source"
        );
    }

    Ok(binding.to_string())
}

fn validate_deps(helpers: &[Helper]) -> Result<()> {
    let helper_map = helpers
        .iter()
        .map(|helper| (helper.module_name.as_str(), helper))
        .collect::<BTreeMap<_, _>>();

    for helper in helpers {
        for dep in &helper.deps {
            if !helper_map.contains_key(dep.as_str()) {
                bail!(
                    "helper `{}` imports missing helper `{dep}`",
                    helper.module_name
                );
            }
        }
    }

    Ok(())
}

fn compute_inline_deps(helpers: &[Helper]) -> Result<Vec<u128>> {
    if helpers.len() > HELPER_BITMAP_BITS {
        bail!(
            "helper count {} exceeds {HELPER_BITMAP_BITS}; migrate helper dependency bitmaps to \
             multiple words",
            helpers.len()
        );
    }

    let helper_indices = helpers
        .iter()
        .enumerate()
        .map(|(index, helper)| (helper.module_name.as_str(), index))
        .collect::<BTreeMap<_, _>>();

    let mut inline_deps = Vec::with_capacity(helpers.len());
    for index in 0..helpers.len() {
        let mut bits = 0u128;
        collect_inline_deps(index, helpers, &helper_indices, &mut bits)?;
        inline_deps.push(bits);
    }

    Ok(inline_deps)
}

fn collect_inline_deps(
    index: usize,
    helpers: &[Helper],
    helper_indices: &BTreeMap<&str, usize>,
    bits: &mut u128,
) -> Result<()> {
    let bit = 1u128 << index;
    if *bits & bit != 0 {
        return Ok(());
    }

    *bits |= bit;

    for dep in &helpers[index].deps {
        let dep_index = helper_indices
            .get(dep.as_str())
            .copied()
            .with_context(|| format!("missing helper `{dep}` during dependency flattening"))?;
        collect_inline_deps(dep_index, helpers, helper_indices, bits)?;
    }

    Ok(())
}

fn generate_mod_rs(helpers: &[Helper]) -> String {
    let mut output = String::new();

    output.push_str(GENERATED_HEADER);
    output.push_str("#![allow(clippy::all)]\n\n");

    for helper in helpers {
        output.push_str("mod ");
        output.push_str(&helper.module_name);
        output.push_str(";\n");
    }

    output.push_str("\n#[allow(non_camel_case_types)]\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n");
    output.push_str("#[repr(usize)]\n");
    output.push_str("pub enum HelperName {\n");
    for helper in helpers {
        output.push_str("    ");
        output.push_str(&helper.ident);
        output.push_str(",\n");
    }
    output.push_str("}\n\n");

    output.push_str("pub const HELPER_COUNT: usize = ");
    output.push_str(&helpers.len().to_string());
    output.push_str(";\n\n");

    output.push_str("#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]\n");
    output.push_str("pub struct HelperBitmap(u128);\n\n");
    output.push_str("impl HelperBitmap {\n");
    output.push_str("    pub const EMPTY: Self = Self(0);\n\n");
    output.push_str("    pub const fn single(name: HelperName) -> Self {\n");
    output.push_str("        Self(1u128 << (name as usize))\n");
    output.push_str("    }\n\n");
    output.push_str("    pub const fn from_bits(bits: u128) -> Self {\n");
    output.push_str("        Self(bits)\n");
    output.push_str("    }\n\n");
    output.push_str("    pub fn contains(self, name: HelperName) -> bool {\n");
    output.push_str("        self.0 & Self::single(name).0 != 0\n");
    output.push_str("    }\n\n");
    output.push_str("    pub fn insert(&mut self, name: HelperName) {\n");
    output.push_str("        self.0 |= Self::single(name).0;\n");
    output.push_str("    }\n\n");
    output.push_str("    pub fn is_empty(self) -> bool {\n");
    output.push_str("        self.0 == 0\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
    output.push_str("impl core::ops::BitOr for HelperBitmap {\n");
    output.push_str("    type Output = Self;\n\n");
    output.push_str("    fn bitor(self, rhs: Self) -> Self {\n");
    output.push_str("        Self(self.0 | rhs.0)\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
    output.push_str("impl core::ops::BitOrAssign for HelperBitmap {\n");
    output.push_str("    fn bitor_assign(&mut self, rhs: Self) {\n");
    output.push_str("        self.0 |= rhs.0;\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("#[derive(Clone, Copy, Debug)]\n");
    output.push_str("pub struct HelperDef {\n");
    output.push_str("    pub name: HelperName,\n");
    output.push_str("    pub local: &'static str,\n");
    output.push_str("    pub import_path: &'static str,\n");
    output.push_str("    #[cfg(feature = \"inline-helpers\")]\n");
    output.push_str("    pub source: &'static str,\n");
    output.push_str("    #[cfg(feature = \"inline-helpers\")]\n");
    output.push_str("    pub deps: HelperBitmap,\n");
    output.push_str("}\n\n");

    output.push_str("pub const ALL: &[HelperDef; HELPER_COUNT] = &[\n");
    for helper in helpers {
        output.push_str("    ");
        output.push_str(&helper.module_name);
        output.push_str("::DEF,\n");
    }
    output.push_str("];\n\n");

    output.push_str("pub fn helper(name: HelperName) -> &'static HelperDef {\n");
    output.push_str("    &ALL[name as usize]\n");
    output.push_str("}\n\n");

    output.push_str("pub fn helper_name(name: &str) -> Option<HelperName> {\n");
    output.push_str("    match name {\n");
    for helper in helpers {
        output.push_str("        \"");
        output.push_str(&helper.ident);
        output.push_str("\" => Some(HelperName::");
        output.push_str(&helper.ident);
        output.push_str("),\n");
    }
    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("impl super::Helpers {\n");
    for helper in helpers {
        output.push_str("    pub fn ");
        output.push_str(&helper.ident);
        output.push_str("(&self) {\n");
        output.push_str("        self.enable(HelperName::");
        output.push_str(&helper.ident);
        output.push_str(");\n");
        output.push_str("    }\n\n");
    }
    output.push_str("}\n\n");

    output.push_str("#[cfg(feature = \"inline-helpers\")]\n");
    output.push_str("pub fn stmts(name: HelperName) -> &'static [swc_ecma_ast::Stmt] {\n");
    output.push_str("    match name {\n");
    for helper in helpers {
        output.push_str("        HelperName::");
        output.push_str(&helper.ident);
        output.push_str(" => ");
        output.push_str(&helper.module_name);
        output.push_str("::stmts(),\n");
    }
    output.push_str("    }\n");
    output.push_str("}\n");

    output
}

fn generate_helper_rs(helper: &Helper, inline_deps: u128) -> String {
    let mut output = String::new();

    output.push_str(GENERATED_HEADER);
    output.push_str("\nuse super::{HelperDef, HelperName};\n\n");
    output.push_str("pub const DEF: HelperDef = HelperDef {\n");
    output.push_str("    name: HelperName::");
    output.push_str(&helper.ident);
    output.push_str(",\n");
    output.push_str("    local: \"");
    output.push_str(&helper.module_name);
    output.push_str("\",\n");
    output.push_str("    import_path: \"@swc/helpers/_/");
    output.push_str(&helper.module_name);
    output.push_str("\",\n");
    output.push_str("    #[cfg(feature = \"inline-helpers\")]\n");
    output.push_str("    source: ");
    output.push_str(&raw_string_literal(&helper.source));
    output.push_str(",\n");
    output.push_str("    #[cfg(feature = \"inline-helpers\")]\n");
    output.push_str("    deps: super::HelperBitmap::from_bits(");
    output.push_str(&format!("0x{inline_deps:032x}"));
    output.push_str("),\n");
    output.push_str("};\n\n");
    output.push_str("#[cfg(feature = \"inline-helpers\")]\n");
    output.push_str("pub fn stmts() -> &'static [swc_ecma_ast::Stmt] {\n");
    output.push_str("    static STMTS: once_cell::sync::Lazy<Vec<swc_ecma_ast::Stmt>> =\n");
    output.push_str("        once_cell::sync::Lazy::new(|| ");
    output.push_str("super::super::parse(DEF.source, DEF.import_path));\n");
    output.push_str("    &STMTS\n");
    output.push_str("}\n");

    output
}

fn raw_string_literal(value: &str) -> String {
    for hashes in 1.. {
        let delimiter = "#".repeat(hashes);
        if !value.contains(&format!("\"{delimiter}")) {
            return format!("r{delimiter}\"{value}\"{delimiter}");
        }
    }

    unreachable!("raw string delimiter search should always terminate")
}
