name: "Publish crates"

env:
  CI: 1
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144
  GIT_AUTHOR_NAME: "SWC Bot"
  GIT_AUTHOR_EMAIL: "bot@swc.rs"
  GIT_COMMITTER_NAME: "SWC Bot"
  GIT_COMMITTER_EMAIL: "bot@swc.rs"

permissions: {}

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish-cargo:
    name: "Publish cargo crates"
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: "main"

      - uses: ./.github/actions/setup-node
        with:
          cache: "false"

      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          toolchain: nightly-2025-05-06

      - name: Install cargo-edit
        uses: taiki-e/install-action@3235f8901fd37ffed0052b276cec25a362fb82e9 # v2.77.7
        with:
          tool: cargo-edit@0.12.2

      - name: Install git-cliff
        uses: taiki-e/install-action@3235f8901fd37ffed0052b276cec25a362fb82e9 # v2.77.7
        with:
          tool: git-cliff@2.8.0

      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.SWC_BOT_SSH }}

      - name: Publish crates
        run: |
          set -eux
          git remote set-url origin "git@github.com:${{ github.repository }}.git"
          git pull --ff-only origin main
          cargo bump
          git push origin main
          git push origin --tags
