/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare function getTargetTriple(): string

export declare function initCustomTraceSubscriber(traceOutFilePath?: string | undefined | null): void

export declare function transform3Times(src: string, options: Buffer, babelTransform?: (...args: any[]) => any | undefined | null, signal?: AbortSignal | undefined | null): Promise<TransformOutput>

export interface TransformOutput {
  code: string
  map?: string
  output?: string
}

/** Hack for `Type Generation` */
export interface TransformOutput {
  code: string
  map?: string
}

