/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare function getTargetTriple(): string

export declare function initCustomTraceSubscriber(traceOutFilePath?: string | undefined | null): void

export declare function transform2Times(src: string, firstOptions: Buffer, babelTransform: (...args: any[]) => any): object

export declare function transform3Times(src: string, firstOptions: Buffer, babelTransform: (...args: any[]) => any, thirdOptions: Buffer): object

export declare function transformOnce(src: string, firstOptions: Buffer): object

export interface TransformOutput {
  code: string
  map?: string
  output?: string
}

export interface TransformOutput {
  code: string
  map?: string
}

/** Hack for `Type Generation` */
export interface TransformOutput {
  code: string
  map?: string
}

